### ISSUE TITLE
Proposed updates to setup workflow

### ISSUE THREAD

**Issue by estrattonbailey** [colepeters/dotfiles#1]
Thanks for the overview and painless setup! I understand you aren't supporting this right now, so no worries, but wanted to post a few extra steps I went through before everything was running smoothly. Perhaps other will find it useful.

**Base Setup**

``` shell
# Clone the repo to into a ".dotfiles" directory in your user directory
git clone git@github.com:colepeters/dotfiles.git ~/.dotfiles

# Switch to the new directory
cd ~/.dotfiles

# Initialise and update Antigen submodule
git submodule init && git submodule update

# Install RCM if it’s not already — you have Homebrew, right?
brew tap thoughtbot/formulae
brew install rcm

# Generate symlinked dotfiles in your ~ directory
rcup -v
```

**Extra Steps**

``` shell
# Install plugins. Run via command line:
vim +PluginInstall +qall
```

If other users are on OS X like me, apparently they'll likely need a newer version of Vim than what shipped with their system. I got it update with the following.

``` shell
# Install Homebrew duplicates 
brew tap homebrew/dupes

# Make sure brew is updated
brew update

# Install Homebrew's vim with Lua (neocomplete dependency)
brew install vim --with-lua
```

They'll also need to make sure their path includes `usr/local/bin:usr/bin`. The usual:

``` shell
# Check PATH
echo $PATH

# Add usr/local/bin to PATH if necessary
sudo vim /etc/paths

# Add `usr/local/bin` to top of the file, should look something like this afterwards.
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

I'd be happy to open a PR as well, if it'd help you out. Cheers!

**Comment by colepeters** [comment]
Most. Delayed. Response. Everrr. Sorry, @estrattonbailey!
As discussed on Twitter, I’m going to be doing some reworking of these, so I’ll close this for now but will keep these points in mind as I make adjustments to the upcoming version. Thanks a lot!
